# Generated by Django 4.0 on 2022-01-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
